### ISSUE TITLE
Wierd wasteland climate in anatolia.

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#1]
The provinces 3243 and 3244 are wastelands mountains in western anatolia but do have the "mild monsoon" climate.
(Not really important just wierd.
![C__Users_jonat_Documents_Paradox Interactive_Europa Universalis IV_mod_Imperium Universalis 2 2 X_map_climate txt - Notepad++ 08 01 2021 16_57_35](https://user-images.githubusercontent.com/59092996/104036201-689cfc00-51d3-11eb-85cd-a0beaf2f5adb.png)
![Europa Universalis IV 08 01 2021 12_26_49](https://user-images.githubusercontent.com/59092996/104036226-6dfa4680-51d3-11eb-868a-ffe0bbeb6efe.png)
![Europa Universalis IV 08 01 2021 12_26_54](https://user-images.githubusercontent.com/59092996/104036237-718dcd80-51d3-11eb-984e-f223c0068f83.png)

)

**Comment by noah1gamble** [comment]
Issues for 1.28 are no longer valid.
