### ISSUE TITLE
Game Crashes after 286

### ISSUE THREAD

**Issue by CoolBlueDJ** [The-Triumvirate/Imperium-Universalis#106]
Every time I load my 1 January 286 save as Rome, I crash only a few days after. Nothing I do fixes this, and I am unable to recreate it when I go to the start menu and set the time to 286 and start a new game. Nothing I did was unusual so I won't go into too much detail, but I will mention that maybe a year prior an event about the spread of Zoroastrian influence popped up. I saw another player reporting this issue after the same event came up, maybe there is a connection? Anyhow, here are the screenshot and logs.
![Screenshot (5)](https://user-images.githubusercontent.com/79792104/109417978-d74d4780-7a15-11eb-8fb5-00936d41c7cd.png)
[error_old.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/6056756/error_old.log)
[error_old_old.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/6056757/error_old_old.log)
[error.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/6056758/error.log)

**Comment by noah1gamble** [comment]
Known issue, still looking into it. Closed due to repeated issue post.
