### ISSUE TITLE
crashing around 285-286

### ISSUE THREAD

**Issue by JanusOvergaard** [The-Triumvirate/Imperium-Universalis#111]
[error.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/6063040/error.log)

got no idea of what exactly is going wrong tbh

**Comment by JanusOvergaard** [comment]
Get to around 285-286 and it crashes every couple months

**Comment by ACommonGuerrillo** [comment]
known issue, error log it's not useful atm
