### ISSUE TITLE
suggestion manpower/force limit suggestions

### ISSUE THREAD

**Issue by adimemir** [The-Triumvirate/Imperium-Universalis#129]
While lowering base manpower to diminish the artificially high manpower reserves of small countries is good, their force limit is still abnormally high due to the base force limit. For example as Athenai, despite having 4 cities and 26 total population (and with 1 granary) I have 8 land force limit while my 6 population 1 city neighbour Plataea has 6 or 7 land force limit. IMO this should be fixed.

Also when you summon the diet as Athenai, nobility missions are unfilled and they automaticly succeed

Typo : When you click cities and see details at bottom-left: Tribesmen should better be renamed to "Manpower"
Redundant text : When you hover over Tribesmen population number , it says 500 manpower increase each pop ; but this is false.
Naming suggestion : "Tribesmen" can be renamed to "Rural"

**Comment by adimemir** [comment]
BTW i don't know how to label this as "suggestion" please show me how.

**Comment by ACommonGuerrillo** [comment]
base force limit will not be reduced as it becomes to unfair for small countries
