### ISSUE TITLE
The 9th Gov tier for indian monarchies is empty.

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#133]
![Europa Universalis IV 04 03 2021 19_00_01](https://user-images.githubusercontent.com/59092996/110008419-fe5c8f80-7d1b-11eb-9c4f-53e679620e38.png)

**Comment by ACommonGuerrillo** [comment]
these are the reforms that let you switch government type, they will continue to be empty until I make some reforms fit for them
