### ISSUE TITLE
Indian missions

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#138]
The indian missions dont give 50 adm points instead of stab if you are already at 3 stab

**Comment by ACommonGuerrillo** [comment]
which Indian mission in Specific?

**Comment by NudelKatze** [comment]
GAN_end_of_the_vedic_period
GAN_prepare_defenses
GAN_tribal_prosperity
GAN_expand_our_dharma
GAN_unite_the_dharma
GAN_gandhara_kambojas
GAN_conquer_saurashtra
GAN_conquer_abhira
GAN_conquer_matsya_surasena
GAN_conquer_avanti
GAN_conquer_kosala
GAN_sunjugate_pulinda

I would also assume this also applies to the other Indian mission trees.
