### ISSUE TITLE
Hinduism doesn't work. 

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#139]
The event custom_religion.27 says it will make me Hindu but it doesn't do that. (It makes loose 5 stab tho?) The decision to switch to Hinduism doesnt do it either.

**Comment by ACommonGuerrillo** [comment]
this is odd, try triggering the event by console

**Comment by NudelKatze** [comment]
No, doesnt work if i trigger it in the console.

**Comment by ACommonGuerrillo** [comment]
the reason might be that the effect enabling the religion and changing religion are in the same line, can you reform via the change religion button?

**Comment by NudelKatze** [comment]
It doesn't work vie the change religion button either.
