### ISSUE TITLE
Kyrenaike - no CBs

### ISSUE THREAD

**Issue by Gezza12** [The-Triumvirate/Imperium-Universalis#143]
Hi,

I'm not getting any CBs playing as Kyrenaike. This issue has existed since the older mod version and figure should now be mentioned. This is regardless of ruler.

**Comment by ACommonGuerrillo** [comment]
There's no problems on the code, you can only declare the cb on your land neighbours so I don't understand your issue

**Comment by Gezza12** [comment]
Indeed, but that's my point of reference. No CBs on Libya or Nasso no matter how much time has passed.

**Comment by noah1gamble** [comment]
> 
> 
> Indeed, but that's my point of reference. No CBs on Libya or Nasso no matter how much time has passed.

We're not going to change the way the mod works.

Eventually there will be mission trees that will give you CBs, as well as events and other stuff. until then this is your only choices.

**Comment by Gezza12** [comment]
So I don't think I'm explaining clearly. I don't have any issue with the way the mod works. I'm trying to articulate that Kyrenaike has no CBs coming up for conquering my neighbours. Please don't take offence; I don't mean to cause any. I love the mod and all the effort you've put in. 

To elaborate, I cannot declare war on any of my neighbours as Kyrenaike without doing no CB. There's no CB showing when I go to declare war. I'm happy to be told I'm missing something or am just a plain moron, but the other nations have border conquests whereas this specific faction has none.

**Comment by Lewa263** [comment]
I just started a game as Kyrenaike and had the Border Conquest CBs on both neighbors. Maybe you're using an outdated broken version of the mod?

**Comment by Gezza12** [comment]
Hmmm, that does tell me there must be something up with my specific copy. I've got the latest version yes. Have no trace of the old mod on this machine. It was wiped ages ago. But perhaps I've done something to the files to cause the issue.

**Comment by Gezza12** [comment]
@noah1gamble @ACommonGuerrillo After further inspection I now suspect the issue may be UI related, as I can see that I do in fact have CBs from my ledger, but no in the DW window. See attached screenshots.

![eu4_4](https://user-images.githubusercontent.com/80108225/110195529-8318ec00-7e89-11eb-8774-0abb58974f0d.png)
![eu4_2](https://user-images.githubusercontent.com/80108225/110195526-7e543800-7e89-11eb-87ee-075a4bbd494e.png)
![eu4_9](https://user-images.githubusercontent.com/80108225/110195531-87450980-7e89-11eb-9ec1-b99cc96654ae.png)

**Comment by noah1gamble** [comment]
This isn't a problem, it's how the game functions.

The ledger shows a lot of improper information.

Closing as there is nothing to be done here.
