### ISSUE TITLE
Bugged responses for monarchy.10 event

### ISSUE THREAD

**Issue by Apani763** [The-Triumvirate/Imperium-Universalis#149]
https://i.imgur.com/nvnVxGB.png

Looking at the game files shows the actual responses are meant to be

 monarchy.10.a:0 "$HEIR$ will not be depositioned"
 monarchy.10.b:0 "The councilors are right, $HEIR_S_PRONOUN$ must go."

**Comment by ACommonGuerrillo** [comment]
this issue has already being fixed
