### ISSUE TITLE
Exploring sea tiles.

### ISSUE THREAD

**Issue by KeranThePolish** [The-Triumvirate/Imperium-Universalis#151]
So i got an event as rome which gave me an explorer and so i went to remove the terra incognita off the mediterranean and i noticed that open sea tiles are not allowed to be explored without the "quest for the new world" idea.
![YLP0YEE](https://user-images.githubusercontent.com/79765184/110237903-da2cc880-7f3e-11eb-9c78-1fd3be8be0bb.png)
This screenshot shows one such happening, but i managed to explore one of them by clicking to explore the sea zone below to force the ship to go through the open sea. Seems that ships can explore these tiles but i cannot order them to do so.

**Comment by ACommonGuerrillo** [comment]
you just need to have an idea that allows you to recruit explorers and conquistadors, though through events you can define explorers the game only allows to do this for the idea itself, sorry but is smth hardcoded
