### ISSUE TITLE
Drop in performance

### ISSUE THREAD

**Issue by pokernerd** [The-Triumvirate/Imperium-Universalis#156]
I was playing normaly, but out of nowhere the game started slowing alot, and every 2 years the game crashes. Can you help?

**Comment by NightWarriorbg** [comment]
This issue has already been fixed, if you are using an older save file than the 3rd of March patch you might have to start a new game or try to clean your save file with the EU4 save cleaner(google).

**Comment by pokernerd** [comment]
I dont think its that because I downloaded the mod yesterday.
