### ISSUE TITLE
Unable to build land reclamation in certain situations

### ISSUE THREAD

**Issue by yeliknewo** [The-Triumvirate/Imperium-Universalis#157]
If there are -1 building slots left then land reclamation can't be built unless you delete a building. An easy fix for this would be to give the Land Reclamation building, not the modifier, something like +5 possible buildings so it can be built even when the province is over full.

**Comment by ACommonGuerrillo** [comment]
no

**Comment by yeliknewo** [comment]
I don't understand. Is this bug intended?
