### ISSUE TITLE
Sparta Military tech 8 crash

### ISSUE THREAD

**Issue by NightWarriorbg** [The-Triumvirate/Imperium-Universalis#16]
Getting to military tech 8 while playing as sparta causes a game crash, nothing useful in error.log.

**Comment by WarKing76** [comment]
Tested Makedonia and they also crash once reaching military tech 8.

**Comment by WarKing76** [comment]
Tested Kyrenaika and crashed the moment I hit military tech 8. I'm suspecting all Greek tags has this issue now.

**Comment by WarKing76** [comment]
Started on the Greco-Persian Wars bookmark where all Greek tags had military tech 8. There were no crashes upon loading in and upgrading mil tech further. And after testing multiple tags from different regions, cultures, and unit models using the same technique, there were no crashes upon reaching military tech 8.
