### ISSUE TITLE
Fabrication available from the diplomacy tab

### ISSUE THREAD

**Issue by 111222111** [The-Triumvirate/Imperium-Universalis#17]
Hello fine people of IU! Just wanted to show you this bug I found with fabrication and the mod. It does not allow me to fabricate by soy through the province view, but, as this picture shows, it will let me fabricate by spy via the diplomacy tab. That is all.
![236850_screenshots_20210210232949_1](https://user-images.githubusercontent.com/28663991/107602770-afc64480-6bf8-11eb-9965-325b6be46390.jpg)

**Comment by NightWarriorbg** [comment]
I think it's not possible to remove the button itself. I tried looking for it but I didn't find anything cause the fabricate claim diplomatic action is hard coded. It's disabled anyway and you can't use it.
