### ISSUE TITLE
Garrison in forts growing at +0

### ISSUE THREAD

**Issue by Dr4GonFire** [The-Triumvirate/Imperium-Universalis#171]
Forts acting wonky as Babylon, once a fort is sieged down, the garrison stays at 100, never recovering up to 2000 or 4000 since garrison growth is +0, not sure if country specific; only running this mod

![wtf](https://user-images.githubusercontent.com/80268793/111203791-b8c67f00-85c5-11eb-9a93-2eb4d843dd0a.png)

**Comment by ACommonGuerrillo** [comment]
build military settlements, they give you garrison growth
