### ISSUE TITLE
Babylon mission for claims on greece, not giving correct claims

### ISSUE THREAD

**Issue by Dr4GonFire** [The-Triumvirate/Imperium-Universalis#178]
The final permanent claims mission for Babylon, the one that gives claims on greece, macedonia, thrace REGION, only gives perma claims on the coast, not the inlands, not sure if intended, but the mission desc says otherwise
![perma](https://user-images.githubusercontent.com/80268793/111762560-6cb75b00-88a1-11eb-9ab0-3691be97e791.png)
![perma not](https://user-images.githubusercontent.com/80268793/111762593-7640c300-88a1-11eb-908a-59ef403bb9be.png)

**Comment by ACommonGuerrillo** [comment]
it is intended that way, you will only get claims in coastal provinces
