### ISSUE TITLE
Suggestion: Adm and Dip rulers skills

### ISSUE THREAD

**Issue by Rinza00** [The-Triumvirate/Imperium-Universalis#186]
I think you did a great job by tieing ruerl's Mil skill to AE level. Would be great to tie Adm skill and Diplo to some mechanics as well. Say Adm to Governing Capacity - it will create a more fluid Empire making, a good ruler will create an empire and then after his death, it goes to shambles. The Diplo skill could be tied to Diplomatic Reputation representing the ability to convince others of your good intentions. For someone with low skill, it will be hard to establish alliances and call to war. 
Also, the Governing Capacity for the greek states is too high in my opinion. At the very beginning, Athens is one of the biggest greek polises and the Gov Capacity is 24 out of 125, meaning I can expand and become 5 times bigger without any issues.

**Comment by CoolBlueDJ** [comment]
'Adm to governing capacity' what a great idea!
