### ISSUE TITLE
Regarding the new "Leadership" idea group...

### ISSUE THREAD

**Issue by redappleseed** [The-Triumvirate/Imperium-Universalis#187]
I'm not sure if this is intentional or not, but I suppose it's worth mentioning because it seems OP to begin with. Within the "Leadership" idea group, there is an idea titled "Military Science" which grants -10% army tradition decay, which is more than enough to negate the base 5% army trad decay. I believe that idea was meant to be -1% army trad decay and that there was a typo for it.
Of course, this isn't game breaking nor does it extremely affect my experience playing this mod, but I just thought it would be worth mentioning to you guys.
![image](https://user-images.githubusercontent.com/81207374/112089774-87aef700-8b4f-11eb-843f-fe0a42074f9c.png)

**Comment by ACommonGuerrillo** [comment]
this issue has already being reported and fixed
