### ISSUE TITLE
Ruler of Kush is 122 years old in Liar Kings bookmark

### ISSUE THREAD

**Issue by Lewa263** [The-Triumvirate/Imperium-Universalis#192]
The history file for Kush has one ruler set taking the throne in 134 and doesn't have the next set until 453, so that first ruler is improbably old in the Liar Kings bookmark in 235. It looks like Wikipedia actually has the rulers of Kush in this period, so this should be fixable with historical info.

**Comment by ACommonGuerrillo** [comment]
even though you have set the death of a ruler in country history, the ruler will not actually die until replace by another scripted one, since there's no other that is scripted this situation happens
