### ISSUE TITLE
Placeholder Provinces visible

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#196]
The place holder provinces are visible if you play as an southern african nation.
Maybe adding a second wasteland around these could be nice
![Europa Universalis IV 27 03 2021 16_08_36](https://user-images.githubusercontent.com/59092996/112725403-5c922200-8f18-11eb-96c9-0519ad9ed1d2.png)

**Comment by ACommonGuerrillo** [comment]
Those ids will be use later on for non wasteland provs
