### ISSUE TITLE
republic.14 event ID

### ISSUE THREAD

**Issue by kapatriot** [The-Triumvirate/Imperium-Universalis#2]
![image](https://user-images.githubusercontent.com/77602329/104873729-2ab07e00-591f-11eb-9df1-bb7114d85885.png)
![image](https://user-images.githubusercontent.com/77602329/104873741-300dc880-591f-11eb-8a3f-ac4061910f4a.png)
![image](https://user-images.githubusercontent.com/77602329/104873748-356b1300-591f-11eb-97c6-de86a4f10125.png)

Unsure if a bug or intended to work this way, three choice event where two of them do not seem to work properly as top one gives a seat to nothing and the second doing nothing at all. Third one seems to be correct since it takes away a stab for refusing.

**Comment by noah1gamble** [comment]
Issues for 1.28 are no longer valid.
