### ISSUE TITLE
You get negative Mana when razing provinces with no pops in the respective category

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#202]
Right now it also almost gives no Cash and Horde Unity making it practically useless.
![Europa Universalis IV 28 03 2021 19_38_52](https://user-images.githubusercontent.com/59092996/112761840-62156800-8ffd-11eb-9aad-f59cfaa9a1f7.png)

**Comment by NudelKatze** [comment]
Ah and the provinces also gain dev.

**Comment by ACommonGuerrillo** [comment]
this is hardcoded sorry about this, it's only possible to change it globally
