### ISSUE TITLE
Slavery Not Enabled, Decision Not Available, Census Bugged

### ISSUE THREAD

**Issue by MumbuCumbu** [The-Triumvirate/Imperium-Universalis#212]
I cannot find anything to do with slavery in my game currently besides for it to be mentioned in my Census decision which also is not working (No pop numbers or changes will ever show up). I heard it may be a decision to abolish or reintroduce slavery but that decision does not show up for me.

**Comment by NudelKatze** [comment]
Slaves are currently disabled because of issues with variables.
Pops take some time to begin growing, especially with a small nation.
Like somewhere between 10 and 30 years.
