### ISSUE TITLE
Horde Invasion CB - Full Invasion of 'X' Peace Option Bug

### ISSUE THREAD

**Issue by JackRubino** [The-Triumvirate/Imperium-Universalis#226]
This was tested only as the Xianbei tag

Declaring war with the Horde Invasion CB enables the Full Invasion of the defender country, which always costs 60 War Score and makes you "form union over x" instead of, I'm assuming, conquering the land. What happens is that the country picking this option forms an actual Personal Union over the defending country and immediately inherits its throne. This cb seems to be usable by any horde that attacks any other horde that borders it. Also, don't know if it'd happen with any country, but on using this peace option on Fergana, a large portion of the map became visible. The localization also has a typo "f**r**oms union"

Steps to reproduce:
- Play as a horde
- Declare Horde Invasion CB
- Pick "Full Invasion of *country name*"

Below some screenshots of the issue:
![immagine](https://user-images.githubusercontent.com/48866730/115970360-0b3e7800-a542-11eb-8681-1d9428ffca9c.png)

![immagine](https://user-images.githubusercontent.com/48866730/115970267-9ec37900-a541-11eb-99ea-2f8b1260d7ca.png)

![immagine](https://user-images.githubusercontent.com/48866730/115970417-86079300-a542-11eb-84dc-b1ba9f6e2460.png)

**Comment by ACommonGuerrillo** [comment]
Invasion cb is reskined
