### ISSUE TITLE
Sikyon uses vanilla unit texture

### ISSUE THREAD

**Issue by AEngelland** [The-Triumvirate/Imperium-Universalis#237]
I don`t know, if this issue was mentiont before, but I found that tag SIC uses vanilla textures. I have the last version of IU from Steam installed and this is the only mod activated.
![20210523133143_1](https://user-images.githubusercontent.com/84663961/119256862-63ad7780-bbcb-11eb-8ad9-28c4e154ae0c.jpg)

**Comment by ACommonGuerrillo** [comment]
try disabling Emperor's unit dlc
