### ISSUE TITLE
Matar Kubileya Spread

### ISSUE THREAD

**Issue by nebula-1010** [The-Triumvirate/Imperium-Universalis#238]
Matar Kubileya is spreading across the world via event. Not sure what causes it but it's happening even to uncolonized provinces in china. Nothing seems to be safe from this really bizarre threat that is caused by ???.

**Comment by NudelKatze** [comment]
Its an event.
This also happens with the "Iranian" religion.

**Comment by NudelKatze** [comment]
specifically its religion.4 and religion.10
