### ISSUE TITLE
Losing permanent claims when releasing nations

### ISSUE THREAD

**Issue by Lorkanius** [The-Triumvirate/Imperium-Universalis#239]
In my gameplay with carthage I noticed losing claims on provinces.
I think it's the 3rd or 4th mission that gives you as a reward a permanent claim on the isles of sicily, sardinia and corsica. My current situation was, that syracuse annexed some sicilian states and after a war and having syracuse release all nations, my claims on those provinces disappeared.

**Comment by NudelKatze** [comment]
This is vanilla eu4.
And its the intended way for game to work.

**Comment by Lorkanius** [comment]
Ouh okay understandable then
