### ISSUE TITLE
Overlapping GUI with Hordes/Native government

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#24]
![Europa Universalis IV 12 02 2021 13_12_24](https://user-images.githubusercontent.com/59092996/107766803-53683f80-6d34-11eb-8cbb-5edc115087b5.png)
In the buildings menu for the natives/hordes this overlaps.

**Comment by NightWarriorbg** [comment]
Can you show me a picture of the whole window not only the bottom?

**Comment by NudelKatze** [comment]
![Europa Universalis IV 12 02 2021 13_41_28](https://user-images.githubusercontent.com/59092996/107769284-0edea300-6d38-11eb-8126-ff4cef0bc773.png)
