### ISSUE TITLE
Special age objective for Rome becomes unavailable if you took the Establish the Principate decision

### ISSUE THREAD

**Issue by HashHashCucu** [The-Triumvirate/Imperium-Universalis#251]
HI there,
This may be intended but it looks more like an overlook for me.

In the Early Hellenistic Period age there is a special age objective for Rome (Roma Invicta), but if you take the Establish Principate decision, the tag changes (from ROM to ROI) and therefore the objective becomes unavailable for you.

Best of luck with the mod! I really enjoy playing it.

**Comment by Vardariotai** [comment]
I'd assume it intended since you can find another ability in imperial age called "pax romana", which is only for ROI.
