### ISSUE TITLE
Crashed after switching back and forth between dates

### ISSUE THREAD

**Issue by UffernOverlord** [The-Triumvirate/Imperium-Universalis#260]
I was switching back and forth between few dates such as fall of jin, punic wars etc to check exactly what nation and at which time I should go for and when i switched back to fall of jin it crashed the game. (I don't know if this might have been issue or not but right before switching to fall of jin from punic wars i changed date around 10 years by myself to check something and then switched to fall of jin. no screenshot available sadly)

**Comment by NudelKatze** [comment]
Well switching dates forth and back is not supported by vanilla, ideally it wouldnt crash but a lot of ugly stuff happens when you do that. (Wrong Gov Reforms, Wrong cores, etc)
