### ISSUE TITLE
Event with missing localization

### ISSUE THREAD

**Issue by Lewa263** [The-Triumvirate/Imperium-Universalis#263]
This event is unreadable because none of it is localized.
![eu4_324](https://user-images.githubusercontent.com/18605346/142734056-7c229e57-4fcf-4c12-885d-dcce5e11236d.png)

**Comment by NudelKatze** [comment]
when did this event appear? did it appear on the loading of a save?

**Comment by Lewa263** [comment]
No, it just popped up unprompted.

**Comment by billiamwill** [comment]
Localization was added by [commit 12d79a4aad5c471098de4e77f5a0cd28d1e9f149](https://github.com/The-Triumvirate/Imperium-Universalis/commit/12d79a4aad5c471098de4e77f5a0cd28d1e9f149) on 30 oct 2021, close it already :-p
