### ISSUE TITLE
Idea localisation errors

### ISSUE THREAD

**Issue by Kulasak113** [The-Triumvirate/Imperium-Universalis#271]
Saw a localisation error then a another one and a another...

Liuqiuan 1st idea: "immoirtality" -> "immortality"
Liuqiuan 1st idea: "chinese explorers" -> "Chinese explorers"
Liuqiuan 4th idea: "nona" -> "none"

Mahan 3th idea: "diligiance" -> "diligence"

Jinhan 2nd idea: "scatter" -> "scattered"
Jinhan 3rd idea: "stablish" -> "establish", "Chinese language" -> "The Chinese language", "custom" -> "customs"
Jinhan 4th idea: "To accomadate a place for where the people of Jinhan to live" > "To accommodate a living place for the people of Jinhan"

Jinhan 4th idea: "gave them as gift" -> "gave them as a gift"
Jinhan 4th idea: "East" -> "east"
Jinhan 6th idea: "The people that form the Jinhan statelets were once the same who founded the state of Jin" -> "The people that form the Jinhan statelets are the descendants from the founders of Jin" 

Jinhan 7th idea: "that formed part of" -> "that formed a part of"
Jinhna 7th idea: "would dominate all other ones" -> "would dominate all the others"

Han commanderies 2nd idea: "specially on the core" -> "specially in the core"
Han commanderies 3rd idea: "and contributed in the sinicization of Korea" -> "and contribute to the sinicization of Korea" 
Han commanderies 7th idea: "The commanderies would as marches" -> "The commanderies would function as marches"
Han commanderies 7th idea: "and later of Xiognu" -> "and later against Xiognu"

Philistian 1st idea: "We philistians" -> "We Philistines"
Philistian 1st idea: "sea peoples" -> "Sea peoples"
Philistian 1st idea: "We have always being" -> "We have always been"
Philistian 1st idea: "Southern Europe" -> "southern Europe"  _-Southern capitalized only when talking about a region Europe is not a region_

Philistian 2nd idea: "onced in the day" -> "back in the day"
Philistian 3rd idea: "we moved" -> "they moved"
Philistian 3rd idea: "from our powerful ships" -> "thanks to their powerful ships"
Philistian 3rd idea: "even raided" -> "they even raided"
Philistian 4th idea: "philistian pantheon" -> "Philistine pantheon"
Philistian 4th idea: "who just an adaptation" -> "who was just an adaptation"
Philistian 4th idea: "good" -> "god"
Philistian 4th idea: "philistian version" -> "Philistine version"
Philistine 4th idea: "and protector of Philistia" -> "and the protector of Philistia"
Philistine 4th idea: "philistian states -> "Philistine states"

Philistine 5th idea: "israelites" -> "Israelites"
Philistine 6th idea: "warrior on Philistia" -> "warriors in Philistia"
Philistine 6th idea: "Kings" -> "kings"
Philistine 6th idea: "numerical disadvanteged" -> "numerical disadvantege"
Philistine 6th idea: "it was only the intervention of the God of Judah the decisive factor" -> "it was only thanks to the intervention of the God of Judah that gave them the decisive factor"

Philistine 7th idea: "The philistian hearland is comprise by" -. "The Philistine heartland is comprised of"

Gojoseon 1th idea: "a descendant of the Heaven descendant of Hwanung and a Bear that become a women" -> " a descendant of Heaven, the descendant of Hwanung and a bear that became a women 

Gojoseon 2nd idea: "korean religion" -> "Korean religion"
Gojoseon 7th idea: "korean capital" -> "Korean capital"

Just saw the first DongYi idea god who writes these.., no thanks i am getting out of this rabbit hole :p

**Comment by AzZotik** [comment]
people with English as their secondary, you would not believe how many got fixed because one of the devs noticed and made them fix some.

**Comment by Kulasak113** [comment]
Well yeah I guessed that, I am not a native english speaker, but there are just so many mistakes. Quick google translator check would fix a lot of these, not to insult anyone but it feels a bit lazy

**Comment by thevnpraetorian** [comment]
It has been something I've been correcting gradually since February, but the sheer amount of things to fix (from the original development team) is a bit overwhelming.

And actually, thank you for reporting these mistakes, because it's very easy to miss little things after staring at thousands of lines of code. I want to make it clear that I am specifically doing my best to correct all grammar mistakes that I stumble upon.
