### ISSUE TITLE
Idea localisation errors 2.

### ISSUE THREAD

**Issue by Kulasak113** [The-Triumvirate/Imperium-Universalis#272]
More free english excersices for me yay :3

Altaic 1st idea: "breed" -> "bred"
Altaic 3rd idea: "later" -> "latter"
Altaic 3rd idea: "by the Indian culture" -> "and the Indian culture"
Altaic 4th idea: "them selfs" -> "themselfs"
Altaic 5th idea: "tocharian" -> "Tocharian"
Altaic 7th idea: "central ans southern Asia" -> "Central Asia and Southern Asia"
Altaic 7th idea: "This" -> "These"
Altaic 7th idea: "india" -> "India

Xiognu 7th idea: "good trained" -> "well trained"

RongDi 2nd idea: "RongDi(Western..." -> "RongDi (Western..."
RongDi 2nd idea: "shaved hair and wearing different clothes" -> "they shave their hair and wear different clothes"

RongDi 4th idea -  _entire thing is badly worded_ 
RongDi 7th idea -  _typographic errors_

Quanrong 1st idea: "The quanrong" -> " The Quanrong"
Quanrong 1st idea: "used to worshipped" -> "used to worship"
Quanrong 2nd idea: "the quanrong" -> "the Quanrong"
Quanrong 3rd idea: "The quanrong" -> "The Quanrong"
Quanrong 4th idea: "the quanrong" -> "the Quanrong"
Quanrong 4th idea: "qing" -> "Qing"
Quanrong 5th idea: "the quanrong" -> "the Quanrong"
Quanrong 6th idea: "the quanrong" -> "the Quanrong"
Quanrong 7th idea: "claim to be descendants" -> "claim to be the descendants"

Steppe Nomands 6th idea: "centimetres  long"    _double space instead of only one_

Saka 1th idea: "saka people" -> "Saka people"
Saka 1th idea: "This legendary had" -> "This legendary plant had"
Saka 1th idea: "saka tribe" -> "Saka tribe"

Saka 2nd idea: "the sakas" -> "the Sakas"
Saka 2th idea: "saka tribes" -> "Saka tribes"

Saka 4th idea: "the sakas" -> "the Sakas" _2x_
Saka 4th idea: "and were practical" -> "and was practical"
Saka 4th idea: "saka innovation" -> "Saka innovation"

Saka 5th idea: "B.C" -> "BC"
Saka 5th idea: "saka elites" -> "Saka elites"
Saka 5th idea: "that were capable of having a fully armored rider and a horse" -> "was capable of carrying a fully armored rider"
Saka 5th idea: "the sakas" -> "the Sakas"
Saka 5th idea: "that were devastating" -> "that was devastating"

Saka 6th idea: "the sakas" -> "the Sakas" _2x_
Saka 6th idea: "xiognu" -> "Xiognu"

Saka 7th idea: "the saka" -> "the Saka"

Chorasamian 1st idea: "chorasamian" -> "Chorasamian"
Chorasamian 4th idea: "chorasamian" -> "Chorasamian"

Albania 1st idea: "albanias" -> "Albanians" _2x_
Albania 2nd idea: "albanian" -> "Albanian"
Albania 3rd idea: "this people was an ancient related to the kassites and that were" -> "these people were historically related to the Kassites that were"
Albania 3rd idea: "much of them would be integrated in Albania" -> "**many** of them would be integrated **into** Albania"
Albania 3rd idea: "albanian" -> "Albanian"
Albania 4th idea: "albanian" -> "Albanian"
Albania 6th idea: "as it allow" -> "as it allowed"

Invasion Scythian 1st idea: "we have being" -> "are"
Invasion Scythian 2nd idea: "cimmerians" -> "Cimmerians"
Invasion Scythian 3nd idea: "euroasian steppe" -> "Euroasian steppe" _for the sake of consistency_ 
Invasion Scythian 4th idea: "pontic steppe" -> "Pontic steppe"
Invasion Scythian 7th idea: "if" -> "If"

Hyrcanian 2nd idea: "The hyrcanians" -> "The Hyrcanians"
Hyrcanian 3rd idea: "enjoyed of" -> "enjoyed"
Hyrcanian 6th idea: "the local hyrcanians" -> "the local Hyrcanians"
Hyrcanian 7th idea: "macedonian" -> "Macedonian"

Dahae 2nd idea: "the dahea" -> "the Dahea"
Dahae 4th idea: "achaemenids to the diadochi" -> "Achaemenids to the Diadochi"
Dahae 4th idea: "dahae mercenaries" -> "Dahae mercenaries"
Dahae 5th idea: "dahea tribe" -> "Dahea tribe"
Dahae 7th idea: "the dahea" -> "the Dahea"
Dahae 7th idea: "the parthians" -> "the Parthians"

Jinhan 6th idea name: "Descendants of Jin State" -> "Descendants of the Jin State"
Dongye 7th idea name: "Ye infantry" -> "Ye Infantry"
Gojoseon 6th idea name: "Rivarly with Yan State" -> "Rivarly with the Yan State"
Buyeo 2nd idea name: "Land for five grains" -> "Land for Five Grains"
Quanrong 1st idea name: "Dog totems" -> "Dog Totems"
Quanrong 6th idea name: "The nine tripod cauldrons" -> "The Nine Tripod Cauldrons"
Quanrong 7th idea name: "The Dog nomads" -> "The Dog Nomads"
Invasion Scythian 4th idea name: "Adapt to settled warfare" -> "Adapt to Settled Warfare"
Invasion Scythian 5th idea name: "Introduce new horse breeds" -> "Introduce New Horse Breeds"
Invasion Scythian 6th idea name: "Ensure the servitude of the Iranians" -> "Ensure the Servitude of the Iranians"
Invasion Scythian 7th idea name: "Embrace new societal structures" -> "Embrace New Social Structures"
Dahae 4th idea name: "Mercenaries of empires" -> "Mercenaries of Empires"

_If only the writer knew that anything to do with a country is always capitalized.._

**Comment by NightWarriorbg** [comment]
Sometimes I wonder if an AI actually writes those lol
