### ISSUE TITLE
Cannot create Custom Nation

### ISSUE THREAD

**Issue by mecejide** [The-Triumvirate/Imperium-Universalis#284]
![20211210231510_1](https://user-images.githubusercontent.com/65686864/145692037-c5d1fa56-e17d-4c38-8f8d-26008ba87873.jpg)
Assuming none of the conditions that are supposed to prevent the player from creating a Custom Nation (such as using too many points), pressing "Done" when designing one results in the above message appearing.

**Comment by AzZotik** [comment]
You are not allowed to use that government reform, pick a proper government reform and it will work.
