### ISSUE TITLE
Merc bug?

### ISSUE THREAD

**Issue by Kulasak113** [The-Triumvirate/Imperium-Universalis#285]
The 5th government rank aka. the Empire rank gives -100 % Possible mercs. But as you can see I can still take mercs with no problems. Also I am not sure if 0 cost to hire a company is intended?
![eu4_77](https://user-images.githubusercontent.com/79542897/145726290-a14f7297-60c8-418a-9fbb-b3fb1378c45e.png)

**Comment by AzZotik** [comment]
Yes hiring mercs is free, you pay for maintenance. But -100% possible mercs I am not sure.

**Comment by BruniTheGit** [comment]
The condottieri mechanic is renamed in IU, and that modifier reduces how many regiments you are able to let other people hire from you.
I think the idea is to keep it a thing for smaller states, but not the big empires.
