### ISSUE TITLE
Chinese Gov Reform Stuck at Tier 1 level 3

### ISSUE THREAD

**Issue by AlabusaRex** [The-Triumvirate/Imperium-Universalis#286]
I'm sorry if I'm an idiot and am missing something simple. 
I am playing as Chu and have finished the level 3 upgrades to progress Tier 1 to level 3. Unfortunately the Tier 4 beginning reform "Develop Land as Much as Possible" won't unlock even though I have multiple Taxman buildings. Included screen of home province, but there are maybe a dozen of them in my realm. 
Do I need this ZhanGuo thing as well? I thought it was a one or the other situation and I have no idea what the ZhanGuo is.
Thanks for your time and this wonderfully amazing mod.

Edit: read stuff, get smart. found "What is the start of ZhanGuo?
It's a global flag that will start when less than 23 countries have their capital in China."
still not sure if this is a requirement **as well** as the taxman. sorry.

![eu4_2](https://user-images.githubusercontent.com/96030461/145737838-90609f0e-6b77-4a40-84f4-e817b8c1c66c.png)
![eu4_1](https://user-images.githubusercontent.com/96030461/145737832-fe0b5777-85b4-4b46-aa77-5d38cff21917.png)

**Comment by AzZotik** [comment]
if you read it carefully it says: Either you already had this reform before and have a Taxman, or have a Taxman when the Warring States start. Also do remember that you can't pick any reform in Reformed Monarchy as they follow a line progression, if you pick third reform on tier 4 you will only be able to unlock every third reform from now on. So make sure you read what each reform row does before you randomly start picking them else you will lock yourself to something you did not want.

**Comment by AlabusaRex** [comment]
Thanks, sorry for the hassle
