### ISSUE TITLE
T

### ISSUE THREAD

**Issue by Jamz262** [The-Triumvirate/Imperium-Universalis#297]
T T T 
![Screenshot (771)](https://user-images.githubusercontent.com/93848140/147553189-b65011e3-e6c1-4b02-a0b7-99afe364aa29.png)

**Comment by AzZotik** [comment]
You do know that players are not supposed to download developer builds?
1. They are full of bugs, crashes and broken features that are not finished yet.
2. They update almost every day and ruin your saves.
3. It's called developer build for a reason. Anything you will report on the dev version will be disregarded and closed.

**Comment by Jamz262** [comment]
got it
