### ISSUE TITLE
Earthquake Event adds population.

### ISSUE THREAD

**Issue by kapatriot** [The-Triumvirate/Imperium-Universalis#3]
![image](https://user-images.githubusercontent.com/77602329/104874526-28e7ba00-5921-11eb-8787-2ae59972dd47.png)

This province had 3 tribal pop until I got the earthquake event which added the other two pops. This also happened when I was playing a horde but with the raze province mechanic, which lowered the tribal pop by 1 but added one of each of the two higher levels of pop.

**Comment by noah1gamble** [comment]
Issues for 1.28 are no longer valid.
