### ISSUE TITLE
Sena Gallica is Sardinian

### ISSUE THREAD

**Issue by ivarjon** [The-Triumvirate/Imperium-Universalis#303]
A province on the Adriatic coast of Italy starts with Sardinian culture and Nuragic religion.
![image](https://user-images.githubusercontent.com/17815813/149635277-aa95593c-d119-488c-a16c-1ef0a2379313.png)

**Comment by NudelKatze** [comment]
Intended.

**Comment by AzZotik** [comment]
A quick google search would tell you this spot was inhabited by them.
