### ISSUE TITLE
Forming The Archipelagos

### ISSUE THREAD

**Issue by Khemesaea** [The-Triumvirate/Imperium-Universalis#305]
Forming the Archipelagos Requires for Milatos, Sparta and Athens to either not exist or to be subjects of Archipelagos (the country you are trying to form) while the wiki page for Archipelagos says that every hellenic nation can form Archipelagos with some additional conditions including the condition that the mentioned countries do not exist or are subjects.
![image](https://user-images.githubusercontent.com/94791895/151675985-7aa06b3e-32b4-40e1-a2cc-2b24c9b83f46.png)
![image](https://user-images.githubusercontent.com/94791895/151675988-a227db6d-5ddf-4802-a807-c9f6d6b12456.png)

**Comment by AzZotik** [comment]
I thought it was kinda obvious anyone but those three can do it, I will edit the page on wiki then.
