### ISSUE TITLE
EU IV Original music and units appering on the mod

### ISSUE THREAD

**Issue by IvanaikosMagno** [The-Triumvirate/Imperium-Universalis#307]
Hello, when I began the game I heard the music of the original EUIV instead of the one of the mod, and the roman units looks kinda victorian:
![20220208224719_1](https://user-images.githubusercontent.com/99294786/153082850-c103f67c-f5b7-401b-9256-6986521ae9f5.jpg)
![20220208225247_1](https://user-images.githubusercontent.com/99294786/153082853-6b9e2de3-2829-4eeb-b6da-c78cb5aac314.jpg)
 I use the DLC subscription and I have the season pass of Imperator Rome that brings new romans units to EUIV

**Comment by AzZotik** [comment]
Imperator Rome Music Submod has grown too large and we had to separate it from the mod itself.
As for the units yes, unless you disable Imperator Rome Unit DLC they will appear like that.

**Comment by NudelKatze** [comment]
The music has been, due to its size, transferred to a music submod.
To get accurate unit models you need to disable all Unit packs, as some of the Unit packs overwrite the mods units.

**Comment by IvanaikosMagno** [comment]
unless you disable Imperator Rome Unit DLC they will appear like that.

How I do that?

**Comment by NudelKatze** [comment]
Have you bought the game over Steam or Epic?

**Comment by IvanaikosMagno** [comment]
Steam

**Comment by NudelKatze** [comment]
In the launcher theres the "DLC" tab. At the very bottom of that list all the Unitpack DLCs should be listed, there you can disable them.

**Comment by IvanaikosMagno** [comment]
it didn't work...
I think it's because this unit pack came with Imperator Rome (which currently isn't even installed)

**Comment by IvanaikosMagno** [comment]
![image](https://user-images.githubusercontent.com/99294786/153091967-08dcf51c-7905-4ca7-a053-6927c4b810f5.png)

**Comment by IvanaikosMagno** [comment]
/\ this is the unit pack, I already try everything, but I cannot find a way to disable it...
