### ISSUE TITLE
Unexpected troop movement

### ISSUE THREAD

**Issue by AndreMuraro** [The-Triumvirate/Imperium-Universalis#308]
Testing if I had conditional access to attack Royal Scythians, I ordered  one army to simply move there and it plotted this route, going from prov 1098 -> 7231. They were actually able to perform the movement, as the screenshots show. I had no diplomatic relations to prov. 7231's owner, other than a conditional acess.

*Obs No other mod installed.

![image](https://user-images.githubusercontent.com/22430585/154580416-1f58a002-9e75-47df-89b2-269f7ba681b6.png)

![image](https://user-images.githubusercontent.com/22430585/154580589-1443a53f-0fa0-45b4-84b6-4b9f24018404.png)

![image](https://user-images.githubusercontent.com/22430585/154580673-99592301-4cc6-4faf-93cf-ccc5c92c3ef0.png)

**Comment by billiamwill** [comment]
These 2 provinces are adjacent according to adjacencies.csv, line 231:
![image](https://user-images.githubusercontent.com/107750034/175354551-81ea8fa2-aa30-49bb-94d9-2c6be39a1d04.png)

1098 should probably be adjacent to 1947 (Piroboridava) instead (it is currently not)
