### ISSUE TITLE
Qin keeps flipping between religions

### ISSUE THREAD

**Issue by nebula-1010** [The-Triumvirate/Imperium-Universalis#312]
Some kind of event is causing the Qin to flip flop between LiYueBaDao and Legalism (or Taoism) anywhere between 1-3 times a month. No other Chinese state that was LiYueBaDao seemed to do this.

**Comment by AzZotik** [comment]
Yeah my bad, I made event to ensure Qin does not die at game start by flipping to LiYueBaDao so Qi will ally it.
Apparently they continue to trigger it and flip back to it every time. Will fix.
