### ISSUE TITLE
Convincing migrants to stay causes enslaved modifier

### ISSUE THREAD

**Issue by Liberater** [The-Triumvirate/Imperium-Universalis#333]
Noticed that everytime i choose the option to convince migrants to stay in the migration event it causes the modifier for choosing the enslave option to appear in the province they were trying to leave from

**Comment by NightWarriorbg** [comment]
What is the event id?

**Comment by billiamwill** [comment]
![image](https://user-images.githubusercontent.com/107750034/218250454-f795daf1-e8c0-449a-ad79-42fb58cb8e95.png)
