### ISSUE TITLE
Focus on inflation decision cost effect is doubled up

### ISSUE THREAD

**Issue by fbserg** [The-Triumvirate/Imperium-Universalis#335]
![image](https://user-images.githubusercontent.com/9066571/190214571-00c486a4-054d-469e-a87f-fb9706acacc5.png)

P.S. inflation is still an absolutely brutal cycle. Hordes don't have the estate privilege to reduce it, so once it gets past -20 it's a lost cause. Thoughts on wiping inflation out by declaring bankruptcy?

**Comment by AzZotik** [comment]
You chose a bad time to use dev build and missed the decision that is specifically aimed to fight inflation early on.
