### ISSUE TITLE
Migratory Tribes Province Size

### ISSUE THREAD

**Issue by Grobcio** [The-Triumvirate/Imperium-Universalis#342]
Description: Whenever I migrate from province to another, province size and id is set to nothing and give 0 rural/urban capacity, what result in constant migration and loosing dev.
![20230217110555_1](https://user-images.githubusercontent.com/79967375/219616453-17956d49-66b2-4f4d-b6a7-281b50cfb39b.jpg)

**Comment by mrkcosta** [comment]
This was due to a common/defines configuration, where a colonization or migration would remove all variables, including those that make Population Capacities run. 
we updated that define some time ago, so it shoulnd't appear again
