### ISSUE TITLE
Sometimes army goes in some province for infinite time. When date of arrival arrives, date move to next day. It often happens, when date of arrival is a next day. And I didn't notice it with AI's army.

### ISSUE THREAD

**Issue by 0oOttOo0** [The-Triumvirate/Imperium-Universalis#363]
I can show it with screenshots and I haven't some video recording program.

**Comment by AzZotik** [comment]
Side effect of sieges, movement in and out of such provinces gets hampered for a while.

**Comment by 0oOttOo0** [comment]
> Побочный эффект осады, передвижение в такие провинции и из них на некоторое время затрудняется.

But my army, that can't to move isn't in province under siege
