### ISSUE TITLE
Pop Calculation tooltip

### ISSUE THREAD

**Issue by ngoinhado** [The-Triumvirate/Imperium-Universalis#368]
![eu4_3](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/a5546b77-c546-44b3-bd4c-b593747846ca)
![eu4_4](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/65309f3b-fb08-4ba5-ba4f-ca257f2b14da)
Ostia has a shrine, which should be only +0.2 Commoner
But in the Province Capacity Detailed => Urban Capacity => Building section => it said "temple (0.5)", which i assume it count Small Temple instead of Shrine?
![eu4_5](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/d2039063-8f4c-4f69-802f-8cd93ca38937)

![eu4_6](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/287ca12b-fa4c-4df3-a8e3-35071bc824ba)
Another example: Roma has Small Temple, which should be only +0.5 Commoner
But in the Province Capacity Detailed => Urban Capacity => Building section => it said "temple (1)", which i assume it count Great Temple instead of Small Temple?

**Comment by mrkcosta** [comment]
Sorry, I see that some values are outdated. I will correct them with the proper values. 

Using Temple in the text means all the temple building chain, as there is not enough space to show all buildings. Same with Theater, Taxes, etc.

**Comment by mrkcosta** [comment]
Corrected! Now tooltips show the real values added in the game (same as the province modifier)
![imagen](https://github.com/The-Triumvirate/Imperium-Universalis/assets/5842997/0ff9b799-7145-405b-afcb-e360534034a7)
