### ISSUE TITLE
Minor things 2

### ISSUE THREAD

**Issue by Krakna21** [The-Triumvirate/Imperium-Universalis#377]
Found a modern art masterpiece in the middle of the desert
![Screenshot (1198)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/71655989-e46f-450c-b9bf-5d60308700c0)
This part of the island of Lesbos is needed for building the Sardis-Susa royal road
![Screenshot (1199)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/a3251efe-5632-4fea-bdd6-5d2c89b5ca19)
This province has no culture
![Screenshot (1200)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/bab906f5-953d-4cb1-8735-ccbeaff7c936)
(I don't know the id)

**Comment by AzZotik** [comment]
Royal Sardeis-Susa road was using 5518 (Methymna) instead of 5517 (Takourtha), fixed in dev.
