### ISSUE TITLE
Potenialy incorrect province modifier

### ISSUE THREAD

**Issue by rgosik** [The-Triumvirate/Imperium-Universalis#378]
![image](https://github.com/The-Triumvirate/Imperium-Universalis/assets/16776617/ddf3afdd-9746-4925-b4b3-48309556e77d)

**Comment by rgosik** [comment]
Mount Geraneia mentions "trouble for passing thorugh"
However it increases the movement speed instead of decreasing it ?

**Comment by AzZotik** [comment]
That's just how it works, friendly movement speed is increase, hostile movement speed is decrease, since it applies to YOUR country, not every single enemy who ever invades you.
