### ISSUE TITLE
Missing Localization!

### ISSUE THREAD

**Issue by Krakna21** [The-Triumvirate/Imperium-Universalis#379]
![Screenshot (1201)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/38f40ab0-f1a2-4d01-bbc4-c52a4927bf80)

(that fleet won't leave the port)

**Comment by Krakna21** [comment]
![Screenshot (1202)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/ead1c971-4f20-42fb-81e0-883e0e35e44f)
I don't control this place.... and this far away island converting to some Anatolian religion is also quite sus

**Comment by AzZotik** [comment]
Limited spread to neighbouring a country with Matar Kubileya, fixed missing loc.
