### ISSUE TITLE
Ramabhar Stupa and Saketa requires cosmopolitanism

### ISSUE THREAD

**Issue by fbserg** [The-Triumvirate/Imperium-Universalis#380]
The wonder requires the Cosmopolitanism government reform that disallows sending missionaries...and as a reward gives you a missionary and missionary strength. 

Same with Saketa wonder right next to it - more missionary power, but disallowed to use missionaries :(

**Comment by AzZotik** [comment]
Likely made when Cosmopolitanism did not have disabling of missionaries, replaced to proselytism in dev.
