### ISSUE TITLE
No capital..?

### ISSUE THREAD

**Issue by Krakna21** [The-Triumvirate/Imperium-Universalis#381]
![Screenshot (1203)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/606cd8b1-64e7-4d8f-a13a-c2535b17ec66)
When I click on their flag it goes to one of my provinces
![Screenshot (1204)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/665f5374-54e1-449f-9b7b-5689d87d14b3)

**Comment by AzZotik** [comment]
fixed in dev, capital was in Ilerda but it belongs to Ilergetae
