### ISSUE TITLE
Something small but painful to the eye

### ISSUE THREAD

**Issue by Krakna21** [The-Triumvirate/Imperium-Universalis#382]
![Screenshot (1205)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/3e2342af-d74b-4e24-8d4f-8fbec7599976)

**Comment by AzZotik** [comment]
BaZhu is a fallback title for having no title, I will take a look why they don't get one, but it would help if you mention what government reform and what primary culture they are.

**Comment by Krakna21** [comment]
> BaZhu is a fallback title for having no title, I will take a look why they don't get one, but it would help if you mention what government reform and what primary culture they are.

Sure, the culture is Tartessian, the 1st tier is Despostism, 2nd tier is Syncretism, tier 3rd is King's land and 4th tier is Focus on agriculture, I also noticed that some future reforms have no name
![Screenshot (1206)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/d908f9ea-614d-4cd5-b11a-284cc856f19f)

**Comment by AzZotik** [comment]
fixed in dev build, emperor title was reserved for BaZhu, now uses EMPEROR_T
