### ISSUE TITLE
Crash at the declaration of war on Gaul

### ISSUE THREAD

**Issue by Zahkklm** [The-Triumvirate/Imperium-Universalis#383]
![image](https://github.com/The-Triumvirate/Imperium-Universalis/assets/78751009/1212b452-9d63-4e95-8fa1-eb9ff2f363fd)
error.log: [error.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/12065296/error.log)

Gaul somehow inherited all Carthaginian lands in a war and for the most of the time game crashes if war is directly declared on them by player.

Recreate Problem: Try to declare war on Gaul on my savegame: https://drive.google.com/file/d/1MB1s6Nae9py9XEc2lYY8YXd5GLyQvMKA/view?usp=sharing

![bugeu4](https://github.com/The-Triumvirate/Imperium-Universalis/assets/78751009/5334c277-90c2-47d0-bbc4-1c83ed5ea306)

Related Crash Folder: [eu4_20230716_124355.zip](https://github.com/The-Triumvirate/Imperium-Universalis/files/12065297/eu4_20230716_124355.zip)

**Comment by Zahkklm** [comment]
This is the exception description from crash folder: "The thread tried to read from or write to a virtual address for which it does not have the appropriate access"

**Comment by AzZotik** [comment]
Colonialism CB issue, will be removed in hotfix, which is sadly delayed.

**Comment by AzZotik** [comment]
You can temporarily solve it by going into:
Imperium-Universalis\common\cb_types
OR
/Steamapps/workshop/content/236850/common/cb_types

put # in front of every line from cb_colonial to }

**Comment by AzZotik** [comment]
Wait a few months for "No Casus Belli" to dissapear and attack.
