### ISSUE TITLE
Bodh Gaya requiring cosmopolitanism

### ISSUE THREAD

**Issue by fbserg** [The-Triumvirate/Imperium-Universalis#385]
Gives missionary benefits, requires reform that disallows missionaries. 

01_monuments 
**line 13691** 
should say 
				FROM = { has_reform = proselytism_reform }

p.s.
Saketa likely as well, as it gives Missionary Strength and requires cosmopolitanism as well. 
**line 3078**

**Comment by AzZotik** [comment]
Fixed alongside all others.
