### ISSUE TITLE
Missing tribe?

### ISSUE THREAD

**Issue by Krakna21** [The-Triumvirate/Imperium-Universalis#387]
Who are the Cantae..? I can't found them anywhere in England or Scotland 
![Screenshot (1210)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/7532995f-c42a-4562-9a03-f908bee41941)

**Comment by AzZotik** [comment]
They are Brythonic tribe of light blue colour that starts in province of Durouernon, being migratory tribe they moved somewhere, given migratory tribes cannot be normally annexed or conquered, they have to be somewhere. Unless under some unknown circumstances migratory tribes don't lose tribal land despite losing their capital province.

**Comment by Krakna21** [comment]
> They are Brythonic tribe of light blue colour that starts in province of Durouernon, being migratory tribe they moved somewhere, given migratory tribes cannot be normally annexed or conquered, they have to be somewhere. Unless under some unknown circumstances migratory tribes don't lose tribal land despite losing their capital province.

They are nowhere to be found, I also checked with the other British tribes but none of them have any diplomatic relation, rival, or federation with the Cantae

**Comment by Krakna21** [comment]
I have one last question not related to that phantom tribe, is there any way to remove my country colour from that desert area? (the map looks kinda ugly)
![Screenshot (1211)](https://github.com/The-Triumvirate/Imperium-Universalis/assets/101092177/67ed43d3-7497-4f25-84fa-5f3faea83d83)
