### ISSUE TITLE
Event An Struggling Empire

### ISSUE THREAD

**Issue by ngoinhado** [The-Triumvirate/Imperium-Universalis#388]
I am Rome, 728 dev pop, just ended a war with result of annexing a nation (10 days ago), then i got this event which confusing me because afaik i am not eligible to get this event, but ingame console said so (????):
1. At least 500 dev: okayish
2. One of the following:
+ Manpower <10%: definitely not since i am 85k/87k manpower
+ Warscore <-5%: i am at peace, how ??? Even when counted my previous war, not even a moment of staying at <5% WS
=> Is this bug or am i misunderstand something?

![eu4_13](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/3b514018-5d6b-4617-a9b6-9fb41586e689)

![eu4_12](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/12c01bf5-0cca-4890-8a70-9fd0d7bd8c77)
![eu4_11](https://github.com/The-Triumvirate/Imperium-Universalis/assets/84243988/587005eb-3d4b-4c2f-b414-5ad3304f524e)

**Comment by AzZotik** [comment]
Very old event, was rewritten in current dev.
