### ISSUE TITLE
Different capacities and growths between Main and Debug events

### ISSUE THREAD

**Issue by DaniloBF** [The-Triumvirate/Imperium-Universalis#391]
Currently, the Debug calculation event for capacities and growth is overcalculating urban capacity, due to the values of some buildings in the PG_urban_buildings_details scripted effect (common/scripted_effects/popgrowth_effects.txt):

- shrine should be 0.2 instead of 0.5 (line 530)
- small_temple should be 0.5 instead of 1.0 (line 531)
- great_temple should be 1.2 instead of 2.0 (line 532)

- big_townhall should be 0.2 instead of 0.4 (line 547)
- government_palace should be 0.4 instead of 0.8 (line 548)
- government_district should be 0.6 instead of 1.5 (line 549)

- great_library should be 1.5 instead of 2.5  (line 561)
- library should be 0.3 instead of 1.0 (line 562)

- mathematician_academy, philosophers_academy and military_academy should be 1.0 each, instead of 2.0  (lines 566, 567 and 568)

- imperial_palace should be 1.0 instead of 3.0 (line 573)
- palace_garden should be 0.5 instead of 1.0 (line 574)

The Main event also has an issue when it calculates how much of rural capacity should go to urban capacity (events/population_capacity.txt). 
In lines 396, 397 and 398, the effect inside each building trigger is set_variable, instead of change_variable, and it is currently overriding the transfer value from institutions.

**Comment by mrkcosta** [comment]
Thanks for noticing, I have updated the values and now the "detailed" scripted effect matches the "normal" one.
