### ISSUE TITLE
Building slots do not open up as population goes up

### ISSUE THREAD

**Issue by kapatriot** [The-Triumvirate/Imperium-Universalis#4]
![image](https://user-images.githubusercontent.com/77602329/104874908-0dc97a00-5922-11eb-8f70-b9fe2d982c61.png)
![image](https://user-images.githubusercontent.com/77602329/104874913-102bd400-5922-11eb-9244-6ce231fd1460.png)

The only building slots open are given by the terrain type, which the mountain province doesn't have therefore it doesn't have a shrine built. We can also see that the population amount required for a new building slot matches the population the province has. Yet in my last ticket, the Skandis province had gained 2 pops going from 3 to 5 yet it unlocked no new slot.

**Comment by noah1gamble** [comment]
Issues for 1.28 are no longer valid.
