### ISSUE TITLE
Rome ask for socii interaction bug in bruttium_area and calabria_area

### ISSUE THREAD

**Issue by chrysalisXu** [The-Triumvirate/Imperium-Universalis#402]
In socci_interaction.txt ask_for_socii_subject 
this interaction is visible to bruttium_area and calabria_area tag.
But in is_allowed, there is a hidden_trigger which specify the capital area and exclude missed these two region.
So players can see this button for tags in that area. satisfy all visible requirements and blocked by an invisible requirement to click it.

Suggestion:
either add these regions to hidden_trigger or delete them from is_visible

**Comment by xaiper010** [comment]
fixed in dev ver
