### ISSUE TITLE
Building Bug

### ISSUE THREAD

**Issue by ArchistrateGene** [The-Triumvirate/Imperium-Universalis#43]
![image](https://user-images.githubusercontent.com/78075887/108620334-8e6e1f80-7466-11eb-995f-124c7563b4ba.png)
![image](https://user-images.githubusercontent.com/78075887/108620340-9928b480-7466-11eb-80d0-8e8662ca8472.png)
Greetings!

There is a bug related to the buildings. The only mods I turned on are uncovered indicator, bigger UI, and fast universalis (since my pc is genuinely dissatisfying). I guess these mods don't affect the gameplay overall, as well as the buildings. Thanks for looking up to this bug report!

Have a nice day, devs!

**Comment by ACommonGuerrillo** [comment]
Our gui is different from vanilla and you are using a mod that alters vanilla gui and is therefore messing with ours
