### ISSUE TITLE
Positive siege modifier after disease breakout

### ISSUE THREAD

**Issue by Closetobegood** [The-Triumvirate/Imperium-Universalis#45]
The AI was unsieging a province and went from a -42% siege progress to 85% after a disease breakout. 
![bug](https://user-images.githubusercontent.com/79406013/108625750-dc762980-744c-11eb-9196-96284ccd7d7d.png)

**Comment by DoktorPFUDOR** [comment]
This is due to an event and has nothing to do with the disease outbreak

**Comment by noah1gamble** [comment]
this is a gameplay mechanic, not a bug
