### ISSUE TITLE
India events happening way to often (ex indian.11 and indian.5)

### ISSUE THREAD

**Issue by moJoDL** [The-Triumvirate/Imperium-Universalis#49]
"ruler dies in hunting" and "Rishi offers service" seem to happen every one or two years. File new_indian.txt.
There is no "mean_time_to_happen" line in the file for these two events.

**Comment by NudelKatze** [comment]
And they probably shoudnt happen for regency councils, i mean how does a regency council get killed in a hunting accident?

**Comment by NudelKatze** [comment]
and regency councils probably shoudnt get rejected as a leader
