### ISSUE TITLE
Missing symbol for Janapadins in land share

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#57]
![Europa Universalis IV 21 02 2021 11_54_29](https://user-images.githubusercontent.com/59092996/108673345-c9626880-74e3-11eb-8292-c22ebd2a15fc.png)

**Comment by ACommonGuerrillo** [comment]
we are aware the infarce in that corner is not displaying our icons, but vanilla, we will try to see a way to fix this
