### ISSUE TITLE
Game crashes every few months.

### ISSUE THREAD

**Issue by SfynxPT** [The-Triumvirate/Imperium-Universalis#60]
I was playing Rome, and played untill about 270 without any problems, but after that the game crashes every few months sometimes after just a few days. 
error log from the most recent one: https://pastebin.com/pGuPgHM0

**Comment by KrunkySmokin** [comment]
Can confirm I've been having a similar problem as Rome around the same date, but I'm into 274 and I'm getting an identical log almost every time. It seems to be completely at random when it will happen, as it has happened to me both while the game time was running, and while the game was paused.

**Comment by HashHashCucu** [comment]
Same here. I play as Rome and in my case before the crash the game starts to lag badly for 2-3 months or so, ending with a CTD. Managed to power through until 280 but it is really difficult to continue now.

**Comment by UnknownGamerYT** [comment]
damn i was lucky i went to the year 300 then and 290 pog
