### ISSUE TITLE
Sacrifice event during war occurs every month

### ISSUE THREAD

**Issue by BaronMadoc** [The-Triumvirate/Imperium-Universalis#72]
Starting a campaign as Judah, every month into a war the “war sacrifice” event pops up meaning I always have to lose a lot of money or 25 mil points per month. Additionally if you guys could upload strategies for nations like Judah that would be much appreciated.

**Comment by ACommonGuerrillo** [comment]
whenever reporting a problem with an event you need to provide us with it's id, you can see that id by typing in the console debug_mode and hovering over the option
