### ISSUE TITLE
Slightly wrong tribal tribute notification sprite.

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#81]
![Europa Universalis IV 23 02 2021 12_23_21](https://user-images.githubusercontent.com/59092996/108837146-20466b80-75d2-11eb-969b-909b1d6f3a0f.png)
Slightly misaligned sprite for tribal tribute notification.

**Comment by NudelKatze** [comment]
this is also the case with some other notifications, but i guess its very minor

**Comment by ACommonGuerrillo** [comment]
the gui wizard haven't looked in to this kek
