### ISSUE TITLE
Institution spread discrepancy

### ISSUE THREAD

**Issue by NudelKatze** [The-Triumvirate/Imperium-Universalis#83]
In the tech tab it says i need a philosopher advisor to spread culture 3.
![Europa Universalis IV 23 02 2021 12_58_36](https://user-images.githubusercontent.com/59092996/108840952-53d7c480-75d7-11eb-9497-15ee0584c091.png)
But when i got to the actual province theres no text saying that a philosopher advisor spreads culture 3.
![Europa Universalis IV 23 02 2021 12_59_58](https://user-images.githubusercontent.com/59092996/108841033-6d790c00-75d7-11eb-9794-9df66e159c78.png)
This is also a problem with other institutions.

**Comment by yeliknewo** [comment]
Not a dev but I think advisors only spread institutions in the capital.

**Comment by ACommonGuerrillo** [comment]
> Not a dev but I think advisors only spread institutions in the capital.

exactly, the philosopher bonus will trigger just in your capital
