### ISSUE TITLE
CTD occuring circa AUC 300

### ISSUE THREAD

**Issue by LT-Rascek** [The-Triumvirate/Imperium-Universalis#86]
Still seeing CTD problems that occur every few months/years in game. Rome circa AUC 300. Attached is the error log. Using latest code pushed to Steam. 

Not certain if related to this bug, but this did not occur until I saved the game and reloaded; game was running slow so I saved, quit, and restarted. It ran faster and then started having CTDs. That _seemed_ to also be an issue previously (i.e., before the latest steam fix), but I can't say for certain.

Error log: [error.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/6032623/error.log)

**Comment by ACommonGuerrillo** [comment]
Your save file has got corrupted due to the update, try a new campaign, sorry

**Comment by LT-Rascek** [comment]
@ACommonGuerrillo I started this game today, after the Steam push. 

OTOH, possibly something got corrupted because I copied the files over into a separate mod folder; I had to jury-rig a work around the 1.28.* bug earlier. I'll purge the mod folder and recopy everything and let you know if it persists.

**Comment by LT-Rascek** [comment]
Cleared the mod folder and recopied everything and started a new game; code is the Steam version. Still having crashes circa 300 AUC. Latest error log:

[error.log](https://github.com/The-Triumvirate/Imperium-Universalis/files/6038895/error.log)
