### ISSUE TITLE
AI countries change ruler every single days

### ISSUE THREAD

**Issue by AverageMapStarringPlayer** [The-Triumvirate/Imperium-Universalis#91]
year is around 280 and a few countries started to change ruler every single days.
it might be related to a change of governement type since it is around this year that you unlock the last tier
And my game is starting to run very poorly

**Comment by ACommonGuerrillo** [comment]
which countries?

**Comment by AverageMapStarringPlayer** [comment]
Vanga and Darada
but if I restart the game other countries take their place
And I found  out that having the "filtering message from other countries" window opened it make the game super slow

**Comment by AverageMapStarringPlayer** [comment]
My mistake
It wasnt every day that they were overthrowing their monarch
It was a lot of time per day
