### ISSUE TITLE
I to have the ruler of nations changing multiple times 

### ISSUE THREAD

**Issue by steloua** [The-Triumvirate/Imperium-Universalis#93]
In a save that cannot go further due to the crash (currently 1 january 293) the ruler of nations such as media, syria and indian minors changed from multiple time in a month to 5 time in a single day. I really think that this might be the origin of the crash as when i used the console command to destroy the nations whom ruler changed each day i was able to continue the game for six months until other nations started to do the same.
Hope this will help

**Comment by NightWarriorbg** [comment]
We will take a look, thank you for the information.
