### ISSUE TITLE
fort level modifiers not working

### ISSUE THREAD

**Issue by CAS1306** [The-Triumvirate/Imperium-Universalis#98]
![Screenshot (3)_LI](https://user-images.githubusercontent.com/79735469/109374922-e7c5cb00-790c-11eb-9433-641f3b0697df.jpg)

**Comment by ACommonGuerrillo** [comment]
sorry about this, but apparently only fort buildings actually change that instead of prov modifiers, will be changing the bonus to defensiveness instead then
